### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by azriel91** [mitchmindtree/daggy#34]
Heya, please could we get a new release with:

* https://github.com/mitchmindtree/daggy/pull/33

It would also contain the fix for https://github.com/mitchmindtree/daggy/issues/28

Thank you

**Comment by azriel91** [comment]
Heya @mitchmindtree, please could we get #33 merged and subsequently a release?

Thanks :bow:

**Comment by azriel91** [comment]
Thanks! and shall copy this here for reference:

> For future reference, if anyone's after a new version, feel free to open a PR with a version bump
> I've think I've setup this repo to auto-publish :)

**Comment by azriel91** [comment]
@mitchmindtree ah, it doesn't have auto publish set up :stuck_out_tongue: needs a `cargo publish`

Looks like the `cargo publish` step was skipped: https://github.com/mitchmindtree/daggy/runs/4054044530?check_suite_focus=true

**Comment by mitchmindtree** [comment]
Ah thanks for the heads up, looks like the repo still had an old revoked key from the days before that old crates.io breach https://github.com/mitchmindtree/daggy/runs/4054053704?check_suite_focus=true#step:4:26.

Should be fixed now :+1:
